### ISSUE TITLE
Excuse me, Could you share the VSCode Extensions for Meteor + VueJS

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor#230]
Excuse me, I am a newbie of `VS Code` for `Meteor + Vue JS`. before I use `WebStorm`.
Now I would like to use `VS Code`, but have problem `autocomplete of npm package in .vue file`
```js
// test.vue
import _ from 'lodash'; // don't autocomplete
export default {
   data(){
      let test = _.sort() // don't autocommplete
   }
}
```
Please help me.

**Comment by MartinBucko** [comment]
You can try this one https://github.com/vuejs/vetur

**Comment by thearabbit** [comment]
I tried issue on `vetur` too, but don't have any solution:
[autocomplete npm package on Vue file](https://github.com/vuejs/vetur/issues/347)

**Comment by ejfrancis** [comment]
@thearabbit in that other issue you created in `vetur` and linked to, someone suggested you install `@types/lodash`. Instead of just following their instructions and running `npm i -D @types/lodash`, you created the exact same issue here. 

I would echo what the user in the other issue said, "This is not a Q/A place for basic npm question. You can find it on Google or StackOverflow.". 

Please don't create issues on GitHub for such unrelated questions like this, this question isn't specific to `vue-meteor` at all and if anything it belongs on a VSCode forum, it doesn't belong on GitHub. An issue on the `vue-meteor` repo should be a real *issue* with `vue-meteor`. A person has to maintain handling/fixing these issues in their own free time, we should be grateful for that and try to help them as much as we can. Creating issues like this one wastes the package creator's time and gets in the way of actual issues that are real problems that need to be solved.

Please close this issue.
