### ISSUE TITLE
Renaming files isn't picked up by build system

### ISSUE THREAD

**Issue by ffxsam** [meteor-vue/vue-meteor#258]
I just did some conventional refactoring and renamed a bunch of .vue files. For some reason, the build system still wants to reference the old names that no longer exist. Even if I remove `.meteor/local/build`, it _still_ uses the wrong filenames!

I had to actually go into the file in question, make some arbitrary change, then save it, causing it to rebuild.

Is webpack maybe not set up properly? It's rebuilding on file modifications but not file renames.

**Comment by ffxsam** [comment]
Side note: if I add something like this to the .vue file:

```js
// random comment to modify the file
```

and save, the app builds fine. If I remove that comment above and save, then it goes back to complaining about trying to import a file that doesn't exist.

**Comment by DamienFF** [comment]
+1

**Comment by mizzao** [comment]
I'm seeing this as well. I renamed a file from `DataView.vue` to `DataViewer.vue`, and the rebuild shows the following error:

![image](https://user-images.githubusercontent.com/2080084/33788840-8804c4b0-dc42-11e7-8536-f43149af6809.png)

I'd been seeing this kind of error for a while and thought I was going crazy since I couldn't even `git grep` for the file it was looking for. Somehow it is remembering the old filenames across a rename.

**Comment by mizzao** [comment]
Seems like this has something to do with Meteor's `caching-compiler`, and other packages providing a build system have run into the same problem: Urigo/angular-meteor#888.

**Comment by mizzao** [comment]
I submitted #278 which (as far as I can tell) fixes this bug.

BTW, as a workaround you can clear `.meteor/local/plugin-cache/akryum_vue-component/` when you rename a file.
